version: "3.0"

services:
  vv-db:
    image: mysql
    volumes:
      - ./docker-volumes/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: "api-backend"
      MYSQL_PASSWORD: "testpassword"
      MYSQL_DATABASE: "virusvis"
    security_opt:
      - seccomp:unconfined

  vv-api-backend:
    build: ./backend/
    restart: always
    ports:
      - 8080:3000
    depends_on:
      - vv-db


  vv-web:
    image: httpd
    restart: always
    ports:
      - 81:80
      - 444:443
    depends_on:
      - vv-api-backend
    volumes: 
      - ./frontend:/usr/local/apache2/htdocs/
